@apiBaseUrl = http://localhost:3000

# GET /events
GET {{apiBaseUrl}}/events


# POST /events
###
# @name createEvent
POST {{apiBaseUrl}}/events
Content-Type: application/json

{
    "name": "New Event",
    "description": "This is a new event",
    "date": "2017-01-01T00:00:00"
}
###
@eventId = {{ createEvent.response.body.id }}

# GET /events/eventId
###
GET {{apiBaseUrl}}/events/{{ eventId }}

###
PATCH {{apiBaseUrl}}/events/{{ eventId }}
Content-Type: application/json

{
    "name": "New Event",
    "description": "This is a new event",
    "date": "2017-01-01T00:00:00",
    "price": 100
}

###
DELETE {{apiBaseUrl}}/events/{{ eventId }}

###
GET {{apiBaseUrl}}/events/{{ eventId }}/spots

###
# @name createSpot
POST {{apiBaseUrl}}/events/{{ eventId }}/spots
Content-Type: application/json

{
  "name": "A3"
}

###
@spotName = {{ createSpot.response.body.name }}

###
POST {{apiBaseUrl}}/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 1234

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "test@test.com"
}


###
// Testing with not found spot
POST {{apiBaseUrl}}/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 1234

{
  "spots": ["A7"],
  "ticket_kind": "full",
  "email": "test@test.com"
}