@apiBaseUrl = http://localhost:8080

# GET /events
###
GET {{apiBaseUrl}}/events


###
# @name createEvent
POST {{apiBaseUrl}}/events
Content-Type: application/json

{
    "name": "New Event",
    "organization": "New Organization",
    "date": "2023-09-20T00:00:00",
    "price": 150,
    "rating": "8",
    "image_url": "https://example.com/image.jpg",
    "created_at": "2023-09-20T00:10:10",
    "location": "New Location"
}

 
# @eventId = {{ createEvent.response.body.id }}
@eventId = 2

# GET /events/{eventId}
###
GET {{apiBaseUrl}}/events/{{ eventId }}


###
PATCH {{apiBaseUrl}}/events/{{ eventId }}
Content-Type: application/json

{
    "name": "Updated Event",
    "organization": "Updated Organization",
    "date": "2023-09-25T00:00:00",
    "price": 200,
    "rating": "9",
    "image_url": "https://example.com/updated-image.jpg",
    "created_at": "2023-09-25T00:10:10",
    "location": "Updated Location"
}

###
DELETE {{apiBaseUrl}}/events/{{ eventId }}

###
GET {{apiBaseUrl}}/events/{{ eventId }}/spots

###
# @name createSpot
POST {{apiBaseUrl}}/events/{{ eventId }}/spots
Content-Type: application/json

{
  "name": "A3",
  "status": "available",
  "event_id": {{ eventId }}
}

###
@spotName = {{ createSpot.response.body.name }}

###
POST {{apiBaseUrl}}/events/{{ eventId }}/reserve
Content-Type: application/json

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "test@test.com"
}


###
// Testing with not found spot
POST {{apiBaseUrl}}/events/{{ eventId }}/reserve
Content-Type: application/json

{
  "spots": ["A7"],
  "ticket_kind": "full",
  "email": "test@test.com"
}
